### ISSUE TITLE
Porting to 1.20.1 To-Do List

### ISSUE THREAD

**Issue by CelestialAbyss** [Project-Vyre/Finality-Genesis#33]
Just a to-do list since I keep forgetting things and have to keep track of things somewhere.
*Still* a work in progress as I am writing this from my phone.

# For Players

If you are a player of the modpack, here is the section for you.

## Removed Mods

Last updated as of `2024-05-19` (YYYY-MM-DD)

- Blue Skies
- Cloud Storage
  - Replaced by Sophisticated Storage & Tesseract
- Ore Growth
- Create: Interior
- ExtendedCrafting, Mystical Agriculture, Mystical Agradditions
  - Resource generation replaced by... you'll see. (Hint: Create automation, chemistry, etc.)
- Iron's Spells 'n Spellbooks
- The Graveyard
  - Nyctophobia
- L_Ender's Cataclysm
  - Lionfish API
- Domestication Innovation

---

# Required Mods

Includes modpack development tools.

- [x] Create
- [x] Exposure 
- [x] Farmer's Delight 
- [x] Finality Core
- [x] Fusion
- [x] Jade + Jade Addons
- [x] KubeJS
- [x] KubeJS Create
- [x] LootJS
- [x] Monobank
- [x] MoreJS
- [x] PonderJS
- [x] ProbeJS
- [x] Salt
- [x] Sooty Chimneys
- [x] Summoning Rituals
- [x] Wares

# Core Experience Mods

- [x] Artifacts
- [x] Grimoire of Gaia
- [x] Quark
- [x] Integrated Structures & Dungeons
- [x] Integrated Stronghold
- [x] Bone Meal Everything
  - Note to self: need to correct name after I wake up.

## YUNG's...

- [x] Better Mineshafts
- [x] Better Jungle Temples
- [x] Better Ocean Monuments
- [x] Better End Island
- [x] Better Witch Huts
- [x] Traveler's Titles

---

# Recipe Integration, Progression & More

- [x] ~~Integrate shapes into early game Create~~
  - This idea will not be implemented into Finality Genesis on 1.20.1 in the near future and has been moved to Finality Mote's 1.20.1 port.
- [x] Integrate Sophisticated Storage with Alex's Caves and other mods.
- [x] Integrate Sophisticated Backpacks with Alex's Caves and other mods.
- [x] Modify recipes for both Sophisticated mods.
- [ ] *Try* to integrate Destroy
- [ ] *Try* to implement custom clockwork meka as a reference to Fontaine from Genshin Impact.
- ~~[ ] Implement the work in progress food items I was already working on since 1.19.2~~
  - Will implement in a later update.
- [x] Change the Tesseract recipe to now utilize Iridium.
- [x] Automate Ender Pearls
- [x] Modify Reliquary recipes to be Create, Summoning Rituals and possibly Ars Nouveau integrated.

## New Materials, Items & Weapons

- [x] Implement Null Matter
- [x] Implement Stardew Valley's iridium to serve as a step above Netherite.
- [x] Implement the Final Singularity as a replacement to the Ultimate Singularity from ExtendedCrafting.

# Create Tooltip Replacing

- [x] Fix Tetra's absurdly long tooltips wherever possible by replacing them with Create tooltips.
- [ ] Replace Reliquary's tooltips with Create tooltips.

---
