### ISSUE TITLE
0.2.1-build.39 To-Do List

### ISSUE THREAD

**Issue by CelestialAbyss** [Project-Vyre/Finality-Genesis#34]
The rest is probably in GitHub commits or if I forgot any. Also typing this on my phone because I'm still tired. *Work in progress.*

- [x] Verify that all recipes still work after the script restructuring.
- [x] Fix Quark's stripped log recipes
- [x] Add sequenced assembly recipes for singularities that can only be crafted with Mechanical Crafters
- [x] Add texture for incomplete sequenced assembly singularities
- [x] Move display names for KubeJS items into lang gen script.
- [x] Verify that there are no Create recipe conflicts that require ingredients to all be present at the same time.
- [x] Refine the Create tooltips added to Aether items.
- [x] Verify that there are no typos in any of the newly added Aether Create tooltips.
- [x] Add the Acuti Ora gem, supposedly Latin for *sharp edge*.
- [x] Add an alternative way to display information for Eversor and Acuti Ora gems.
- [x] Add cutting recipes for cutting Eversor gems into Acuti Ora gems.
- [x] Add additional tooltips to blocks and items primarily from the Aether mod to help explain their usage.
  - [x] Add an item to explain how to use Ender Drawers from Functional Storage.
- [x] Fix REI categorization for the newly implemented singularities.
  - [x] Altar
  - [x] Incubator
  - [x] Ambrosium Shard
    - [x] Add info on renewal methods
  - [x] Holystone
    - [x] Add renewal recipes for Zanite, Gravitite and Ambrosium ore.
  - [x] Icestone (Apparently it was always there, just didn't see it)
  - [x] Holystone Tools
  - [x] Zanite Tools
  - [x] Zanite Axe and its ability to strip golden amber
  - [x] Gravitite Tools
  - [x] Gravitite Axe and its inability to strip logs safely due to blocks floating into the sky, never to be seen again.
  - [x] Gravitite Armor
  - [x] Valkyrie Tools
  - [x] Valkyrie Lance
  - [x] Valkyrie Armor
  - [x] Phoenix Armor
  - [x] Obsidian Armor
- [x] GUI fixes after the release of FancyMenu v3.
- [x] Re-implement acquisition method of glowstone dust that was removed a few versions back and re-implement it for Soul Soil.
- [x] Implement alternative recipes for making dirt without the use of Bone Meal.
- [x] Implement the Terraria mechanic of Regeneration when standing in Honey. In this case, Create's Honey.
- [x] Implement player fluid check so players actually get affected in certain ways when touching them.
- [x] Address Nether Wart not being affected by Lil Wing's Swallow Tail Butterflies.
- [x] Give more uses to Echo Shards.
  - [x] Converting certain blocks into sculk related blocks.
- [x] Uncrafting recipes with Create. (Partial implementation)
- [x] Implement the Deconstructor / Undo Button
  - [x] Undo Crying Obsidian to Obsidian
  - [x] Undo Soul Sand to Sand
  - [x] Undo Soul Soil to Soil
  - [x] Undo Train Casing to Brass Casing + Sturdy Sheet
  - [x] Undo Andesite Casing to Andesite Alloy + Stripped Spruce Log
  - [x] Undo Brass Casing to Brass Ingot + Stripped Dark Oak Log
  - [x] Undo Copper Casing to Copper Ingot + Stripped Spruce Log
- [x] First implementation of deconstruction recipes.
  - [x] Uncraft crossbows and bows
  - [x] Uncraft shears, flint and steel.
- [x] Summoning rituals for summoning vanilla mobs.
  - [x] Warden
  - [x] Witch
  - [x] Stray
  - [x] Drowned
  - [x] Husk
  - [x] Squid
  - [x] Glow Squid
  - [x] Slime
- [x] Summoning rituals for Lil' Wings butterflies.
- [x] Finish Just More Cakes! Implementation, recipes and all with integration with Crafts & Additions.
  - [x] All JMX icing mixing recipes if applicable to the specified cake.
  - [x] Triple Tiered Cake sequenced assembly recipe.
  - [x] Icing filling recipes if applicable to the specified cake.
- [x] Fix chocolate recipes on Neapolitan's side of things.
- [x] Fix milk recipe from Create Slice & Dice.
- [x] Implement recipes to make Upgraded Netherite Essence without requiring Dragon's Breath.
- [x] Give Wandering Traders the ability to trade Chorus Fruit.
