### ISSUE TITLE
0.2.1-build.50-mc1.19.2 To-Do List

### ISSUE THREAD

**Issue by CelestialAbyss** [Project-Vyre/Finality-Genesis#35]
- [x] Implement Tinker's Construct recipe modifications
- [x] Awaiting release of Roadrunner on 1.19.2 for further optimization.
- ~~Address Mystical Fertilizer not being able to be used on certain Mystical Agriculture crops. If not possible then revoke this from the task list.~~ It appears this can't be overriden.
- ~~Strengthen the Create route of material automation to have an edge over Mystical Agriculture to reward complex automation.~~ Push this back to another update.
- ~~Implement long awaited additional texture changes.~~ Edit: Pushing this to another update or saved for 1.20.1 or 1.20.6.
- [x] Address potential breaking changes from the major Iron's Spellbooks update.
