### ISSUE TITLE
0.2.1-build.51-mc1.19.2 To-Do List

### ISSUE THREAD

**Issue by CelestialAbyss** [Project-Vyre/Finality-Genesis#36]
- [x] Fix KubeJS bossDeathToast not defined error
- [x] Fix Malum wood not being able to be turned into chests for some odd reason... It's weird. Edit: It's my fault for not writing compatibility.
- [x] Fix Tinkers' Construct Beacon recipe being present...
- [x] Fix missing blasting recipes

**Comment by CelestialAbyss** [comment]
Blasting recipes have also been mysteriously removed for some reason, could possibly be due to Tinkers' Construct but currently unconfirmed.

**Comment by CelestialAbyss** [comment]
The above issue was due to a typo... Addressed in commit 4e662b9.
