### ISSUE TITLE
Brass Casing GUI To-Do for 1.20.1

### ISSUE THREAD

**Issue by CelestialAbyss** [Project-Vyre/Finality-Genesis#37]
# Recipe Viewer GUIs

Just a to-do list to keep track of the ones I need to retexture.

## JEI

- [x] Vanilla MC
- [ ] Create
- [ ] Farmer's Delight
  - [ ] Cooking
  - [ ] Cutting Board
  - [ ] Decomposition
- [ ] Caupona
  - [ ] Aspic Thawing (Brazier)
  - [ ] Aspic Thawing (Pot)
  - [ ] Boiling
  - [ ] Container Draining
  - [ ] Container Filling
  - [ ] Resting Conversion
  - [ ] Aspic Setting
  - [ ] ...
- [ ] Summoning Rituals
  - [ ] Summoning Altar
- [ ] The Aether
  - [ ] Accessory Freezable
  - [ ] Ambrosium Enchanting
  - [ ] Enchanting
  - [ ] Freezing
  - [ ] Aether Fuel
  - [ ] Icestone Freezable
  - [ ] Incubating
  - [ ] Placement Conversion
  - [ ] Repairing
  - [ ] Swet Ball Conversion
- [ ] Alex's Caves
  - [ ] Nuclear Furnace Blasting
  - [ ] Spleunkery Table Translation
- [ ] Apotheosis
  - [ ] Infusion Enchanting
  - [ ] Fletching
  - [ ] Gem Cutting
  - [ ] Salvaging
  - [ ] Spawner Modification
- [ ] Exposure
  - [ ] Printing
  - [ ] Stacking Photographs
- [ ] Just Enough Resources
  - [ ] Dungeon Chests
  - [ ] Enchantments
  - [ ] Mob Drops
  - [ ] Plant Drops
  - [ ] Villager Trades
  - [ ] World Gen
- [ ] Salt
  - [ ] Growing Salt Crystals
  - [ ] Water Evaporation
- [ ] Sooty Chimneys
  - [ ] Soot Covering
  - [ ] Soot Scraping
- [ ] Some Assembly Required
  - [ ] Sandwiching Station
- [ ] Architect's Palette
  - [ ] Warping
- [ ] Destroy
  - [ ] Aging
    - Might be removed or heavily modified on the full release of Destroy.)
  - [ ] Centrifugation
  - [ ] Charging
    - Might be removed or heavily modified on the full release of Destroy.)
  - [ ] Distillation
  - [ ] Electrolysis
    - Might be removed or heavily modified on the full release of Destroy.)
  - [ ] Generic Reaction
    - Might share some assets with another recipe type, need to check.)
  - [ ] Phytomining
- [ ] Just Enough Beacons
  - [ ] Beacon Base Blocks, Beacon Payments & Conduit Frame Blocks
    - Presumably these all share the same GUI texture.
- [ ] Reliquary
  - [ ] Alkahestry Tome Charging & Crafting
  - [ ] Apothecary Cauldron
  - [ ] Infernal Tear
  - [ ] Apothecary Mortar
- [ ] The Bumblezone
  - [ ] Bee Queen Color Trades
  - [ ] Bee Queen Trades
- [ ] Productive Bees
  - [ ] Advanced Beehive
  - [ ] Bee Breeding
  - [ ] Bee Conversion
  - [ ] Bee Fishing
  - [ ] Bee Flowering
  - [ ] Bee Spawning
  - [ ] Heated Centrifuge & Centrifuge
  - [ ] Block Conversion
  - [ ] Bottler
  - [ ] Incubation
- [ ] Rats
  - [ ] Cheesemaking
  - [ ] Chef Rat
- [ ] Rechiseled
  - [ ] Chiseling
- [ ] Lychee
  - [ ] Item Burning
- [ ] Ore Growth
  - [ ] Crystal Growth
- [ ] Lightman's Currency
  - [ ] Coin Mint
  - [ ] Ticket Station
- [ ] FTB Quests
  - [ ] Quests

## REI

- [ ] ...

## EMI

Need to check first if it uses existing JEI / REI textures.

- [ ] EMI itself because I did not bother to do so just yet.
- [ ] Vanilla MC
- [ ] ...
